$(document).ready(function() {
	$(".fr-grow").parent().addClass("fragment grow");
	$(".fr-shrink").parent().addClass("fragment shrink");
	$(".fr-fade-in").parent().addClass("fragment fade-in");
	$(".fr-fade-out").parent().addClass("fragment fade-out");
	$(".fr-fade-up").parent().addClass("fragment fade-up");
	$(".fr-fade-down").parent().addClass("fragment fade-down");
	$(".fr-fade-left").parent().addClass("fragment fade-left");
	$(".fr-fade-right").parent().addClass("fragment fade-right");
	$(".fr-current-visible").parent().addClass("fragment current-visible");
	$(".fr-highlight-current-red").parent().addClass("fragment highlight-current-red");
	$(".fr-highlight-current-green").parent().addClass("fragment highlight-current-green");
	$(".fr-highlight-current-blue").parent().addClass("fragment highlight-current-blue");
	$(".fr-highlight-red").parent().addClass("fragment highlight-red");
	$(".fr-highlight-green").parent().addClass("fragment highlight-green");
	$(".fr-highlight-blue").parent().addClass("fragment highlight-blue");
});

$(document).ready(function() {
    $('.black-bg').parent().addClass('black-bg-parent');
    $('.gray-bg').parent().addClass('gray-bg-parent');
    $('.grey-bg').parent().addClass('grey-bg-parent');
    $('.silver-bg').parent().addClass('silver-bg-parent');
    $('.white-bg').parent().addClass('white-bg-parent');
    $('.maroon-bg').parent().addClass('maroon-bg-parent');
    $('.red-bg').parent().addClass('red-bg-parent');
    $('.magenta-bg').parent().addClass('magenta-bg-parent');
    $('.fuchsia-bg').parent().addClass('fuchsia-bg-parent');
    $('.pink-bg').parent().addClass('pink-bg-parent');
    $('.orange-bg').parent().addClass('orange-bg-parent');
    $('.yellow-bg').parent().addClass('yellow-bg-parent');
    $('.lime-bg').parent().addClass('lime-bg-parent');
    $('.green-bg').parent().addClass('green-bg-parent');
    $('.olive-bg').parent().addClass('olive-bg-parent');
    $('.teal-bg').parent().addClass('teal-bg-parent');
    $('.cyan-bg').parent().addClass('cyan-bg-parent');
    $('.aqua-bg').parent().addClass('aqua-bg-parent');
    $('.blue-bg').parent().addClass('blue-bg-parent');
    $('.navy-bg').parent().addClass('navy-bg-parent');
    $('.purple-bg').parent().addClass('purple-bg-parent');
    $('.o-gray1-bg').parent().addClass('o-gray1-bg-parent');
    $('.o-gray2-bg').parent().addClass('o-gray2-bg-parent');
    $('.o-gray3-bg').parent().addClass('o-gray3-bg-parent');
    $('.o-orange-bg').parent().addClass('o-orange-bg-parent');
    $('.o-blue-bg').parent().addClass('o-blue-bg-parent');
    $('.o-yellow-bg').parent().addClass('o-yellow-bg-parent');
    $('.o-green-bg').parent().addClass('o-green-bg-parent');
    $('.o-magenta-bg').parent().addClass('o-magenta-bg-parent');
});